### PR TITLE
Support for typescript 3.5

### PR DESCRIPTION
**Pull request by dpvc**
This PR makes adjustments to accommodate `tsc` version 3.5.2 and its stronger checking of some types.  In particular, the mix-in code had to be modified to not use the generics for the subclass as generics for the base class.  For now, this is done by using `any` in place of the generics, but that should be changed after v3 is released to be a more robust approach.

### CODE REVIEW

**Comment by dpvc** [comment]
This resolves issue #309.

**Comment by zorkow** [comment]
I get:
```found 215 high severity vulnerabilities```
An `npm audit` fixes that but obviously changes the `package-lock.json`. I think we should fix the vulnerabilities before merging this.

**Comment by dpvc** [comment]
> I get `found 215 high severity vulnerabilities`

This was fixed in [this commit](https://github.com/mathjax/mathjax-v3/commit/31f69d77414571e6dc89d125d8d9bc322272ed15), which I did directly on the master branch without review, since it was showing on the GitHub page directly (they do that now).  When I merge with `master`, an `npm audit` shows no problems.

**Comment by dpvc** [comment]
PS, the conflict in `package.json` is the one that resolves the issue (it is the update to `lodsash`).  By including *both* lines, that should clear up the errors.

**Comment by zorkow** [comment]
Sounds good.

**Pull request merged**
