### PR TITLE
Changes getColor to public.

### PR DESCRIPTION
**Pull request by zorkow**
Missed that one in my last review. Sorry!

### CODE REVIEW

**Comment by zorkow** [comment]
@OmarIthawi Found a last little problem. Sorry for not spotting that earlier.

**Comment by dpvc** [comment]
Approved

**Comment by zorkow** [comment]
@OmarIthawi No, it simply does not compile otherwise, as we are trying to use `getColor` from within the `ColorMethods` module.

**Comment by zorkow** [comment]
@dpvc  Thanks for the quick turnaround!

**Comment by zorkow** [comment]
@OmarIthawi 
> I made it private, and it worked, so I didn't over think it.

You must be using different compiler settings, then. It did not work for me. 

> mathjax3-ts/input/tex/color/ColorMethods.ts(66,30): error TS2341: Property 'getColor' is private and only accessible within class 'ColorModel'.
> ...

**Comment by OmarIthawi** [comment]
It might be just me overlooking it, and using a older version of the compiled code. Thanks for catching it @zorkow!

**Pull request merged**
